import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { build } from "esbuild";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");
const CALAMUS_PKG = process.env.CALAMUS_PKG
  ? resolve(process.env.CALAMUS_PKG)
  : resolve(ROOT, "vendor", "calamus-wasm");

const GENERATED_DIR = resolve(ROOT, "src", "generated");
const OUTPUT = resolve(ROOT, "silverbullet-calamus.plug.js");

// --- Step 1: Read WASM and encode as base64 ---
const wasmPath = resolve(CALAMUS_PKG, "calamus_wasm_bg.wasm");
if (!existsSync(wasmPath)) {
  console.error(`WASM file not found: ${wasmPath}`);
  process.exit(1);
}

const wasmBytes = readFileSync(wasmPath);
const wasmBase64 = wasmBytes.toString("base64");
console.log(
  `WASM: ${wasmPath} (${wasmBytes.length} bytes, ${wasmBase64.length} base64 chars)`,
);

// --- Step 2: Read calamus JS bindings and strip for iframe use ---
const jsBindingsPath = resolve(CALAMUS_PKG, "calamus_wasm.js");
const jsBindingsRaw = readFileSync(jsBindingsPath, "utf-8");

// Strip export keywords and the default export line for iframe inlining.
// We keep initSync and the internal functions, but remove ES module syntax.
const jsBindingsStripped = jsBindingsRaw
  .replace(/^export\s+function\s+/gm, "function ")
  .replace(/^export\s+\{[^}]*\};?\s*$/gm, "")
  .replace(/^export\s+default\s+.*$/gm, "")
  // Remove the @ts-self-types comment
  .replace(/^\/\*\s*@ts-self-types.*\*\/\s*$/gm, "")
  // Replace import.meta.url (ES module syntax) — only used in async init() which we don't call
  .replace(/import\.meta\.url/g, "undefined");

// --- Step 3: Write generated module ---
mkdirSync(GENERATED_DIR, { recursive: true });

const generatedModule = `// Auto-generated by scripts/build.ts — do not edit
export const WASM_BASE64 = ${JSON.stringify(wasmBase64)};
export const CALAMUS_JS_BINDINGS = ${JSON.stringify(jsBindingsStripped)};
`;

writeFileSync(resolve(GENERATED_DIR, "wasm-bundle.ts"), generatedModule);
console.log(`Generated: src/generated/wasm-bundle.ts`);

// --- Step 4: Bundle with esbuild ---
const result = await build({
  entryPoints: [resolve(ROOT, "src", "entry.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  minify: true,
  outfile: OUTPUT,
  logLevel: "info",
});

if (result.errors.length > 0) {
  console.error("Build failed:", result.errors);
  process.exit(1);
}

console.log(`Built: ${OUTPUT}`);
